apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec: # We are saying that Kubernetes must find storage that meets below requirements
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # 2GB
